redis:
    image: redis:latest
    container_name: cms_redis
    ports:
      - "6379:6379"
    networks:
      - cms_network

  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: cms_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - cms_network